<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Authors\" />
    <Folder Include="Auth\" />
    <Folder Include="Categories\" />
    <Folder Include="Dashboard\" />
    <Folder Include="Languages\" />
    <Folder Include="Loans\" />
    <Folder Include="Members\" />
    <Folder Include="Publishers\" />
    <Folder Include="Settings\" />
  </ItemGroup>

</Project>
