<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5155bf54-0718-4f78-80a0-831da130bbe0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexKutuphane.Application\NexKutuphane.Application.csproj" />
    <ProjectReference Include="..\NexKutuphane.Contracts\NexKutuphane.Contracts.csproj" />
    <ProjectReference Include="..\NexKutuphane.Domain\NexKutuphane.Domain.csproj" />
    <ProjectReference Include="..\NexKutuphane.Infrastructure\NexKutuphane.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>
